acme_blog_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeBlogBundle:Default:index }
acme_blog_create:
    path:     /create
    defaults: { _controller: AcmeBlogBundle:Default:create }
acme_blog_get:
    path:     /get/{id}
    defaults: { _controller: AcmeBlogBundle:Default:show }
